### ISSUE TITLE
Does vectordb search the document only with embedding?

### ISSUE THREAD

**Issue by juicyjung** [jina-ai/vectordb#59]
Thank you for your great project.
It's really good.

My question is "Does vectordb search the document only with embedding?"
I mean the search algorithm.

```
class ToyDoc(BaseDoc):
    text: str = ""
    embedding: NdArray[1536] 
```

If I set ToyDoc Class like this. (refer to your examples)
What does the vairable "text" do?

Just for save the information related to embedding?

Or use some search algorithm for "text" too?

**Comment by JoanFM** [comment]
Hey @juicyjung ,

It is only used to sabe the informstion so that at retrieve time u have the trxt and do not need to map embeddings to IDs on ur own

**Comment by juicyjung** [comment]
um..
I don't get it.

1. I don't need to map text and embedding??

2. vectordb search by text? not embedding?

3. If I add some variable to save more information, It doesn't affect to the search right?

**Comment by juicyjung** [comment]
> Hey @juicyjung ,
> 
> It is only used to sabe the informstion so that at retrieve time u have the trxt and do not need to map embeddings to IDs on ur own

um..
I don't get it.

I don't need to map text and embedding??

vectordb search by text? not embedding?

If I add some variable to save more information, It doesn't affect to the search right?

**Comment by JoanFM** [comment]
Exactly, the search is done only by EMBEDDING. Other fields are just to store them without any effect on results.

**Comment by juicyjung** [comment]
I got you bro, Thanks a lot
