### ISSUE TITLE
Instruction for using the dockerfile is not found in readme file

### ISSUE THREAD

**Issue by ai-naymul** [jina-ai/vectordb#60]
There is no instruction for how use the dockerfiles of vectordb in the readme file, Should we work on that?

**Comment by JoanFM** [comment]
What would u use  them for?

**Comment by ai-naymul** [comment]
> What would u use them for?

Oh... I am extremely sorry for that I didn't notice that the project is already in pypi.
I am so sorry for creating a useless issue....
