### ISSUE TITLE
Missing `__validators__` property with `pydantic>=2`

### ISSUE THREAD

**Issue by gabe-l-hart** [jina-ai/vectordb#67]
## Description

When instantiating an `InMemoryExactNNVectorDB` instance using `pydantic>=2`, an exception is raised about the `__validators__` attribute being missing. This does not happen with `pydantic<2`.

## Environment

* M1 MacBookPro (M1 Max arm chip)
* Python 3.11.5 (`conda`)
* Packages:
    * `vectordb==0.0.20`
    * `docarray==0.40.0`
    * `pydantic==2.3.0`
    * `pydantic-extra-types==2.3.0`
    * `pydantic-settings==2.1.0`
    * `pydantic_core==2.6.3`

## Workaround

When I add the `__validators__` property (even with a value of `None`), the bug is avoided and the database works as expected. I'm not clear if it's functioning with less validation than desired since [this line](https://github.com/jina-ai/vectordb/blob/main/vectordb/utils/create_doc_type.py#L18) will result in `__validators__=None`, but the DB is able to store and retrieve documents just fine.

## Repro

```py
from docarray import BaseDoc
from vectordb import InMemoryExactNNVectorDB

class BrokenDoc(BaseDoc):
    text: str
    # Uncomment this to work around the bug!
    # __validators__ = None

db = InMemoryExactNNVectorDB[BrokenDoc]()
```

## Error

```
Traceback (most recent call last):
  File "vdb_repro.py", line 8, in <module>
    db = InMemoryExactNNVectorDB[BrokenDoc]()
         ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/opt/miniconda3/envs/env/lib/python3.11/site-packages/vectordb/db/base.py", line 40, in __class_getitem__
    class VectorDBTyped(cls):  # type: ignore
  File "/opt/miniconda3/envs/env/lib/python3.11/site-packages/vectordb/db/base.py", line 42, in VectorDBTyped
    _executor_cls: Type[TypedExecutor] = cls._executor_type[item]
                                         ~~~~~~~~~~~~~~~~~~^^^^^^
  File "/opt/miniconda3/envs/env/lib/python3.11/site-packages/vectordb/db/executors/typed_executor.py", line 71, in __class_getitem__
    output_schema = create_output_doc_type(input_schema)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/env/lib/python3.11/site-packages/vectordb/utils/create_doc_type.py", line 18, in create_output_doc_type
    __validators__=input_doc_type.__validators__,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/env/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 210, in __getattr__
    raise AttributeError(item)
AttributeError: __validators__
```

**Comment by JoanFM** [comment]
Hey @gabe-l-hart ,

Does it also happen if you use a Document with an `embedding` field?

**Comment by JoanFM** [comment]
I see now. 

Compatibility with `pydantic>v2` is not guaranteed because Jina dependency does not gurantee it yet

**Comment by gabe-l-hart** [comment]
Hi @JoanFM! Totally makes sense that `pydantic>=2` is not supported. The dependency is coming in as a transitive dep from `docarray` ([here](https://github.com/docarray/docarray/blob/main/pyproject.toml#L38)). In `docarray`, there is no upper bound on `pydantic` specified, so since `vectordb` does not explicitly declare `pydantic<2` in [requirements.txt](https://github.com/jina-ai/vectordb/blob/main/requirements.txt), `pip` will resolve to the latest `pydantic` when doing `pip install vectordb` which will cause this error.

There are two candidate solutions that I can see:

1. Add `pydantic<2` to `requirements.txt`. This would ensure that `pip install vectordb` gets a compatible version of `pydantic`, but it _would_ prevent `vectordb` from being used in conjunction with libraries that require `pydantic>=2`
2. Change [this line](https://github.com/jina-ai/vectordb/blob/main/vectordb/utils/create_doc_type.py#L18) to `__validators__=getattr(input_doc_type, "__validators__", None)` (default to `None` if the `__validators__` attr isn't present).

Solution (2) is pretty simple, but I haven't plumbed the depths of `vectordb`, `docarray`, or `pydantic` to understand what (if any) unintended consequences it would have.

**Comment by gabe-l-hart** [comment]
For context on why I submitted the issue, I've really enjoyed `vectordb` in a sample project that uses [caikit](https://github.com/caikit/caikit) (one of my primary projects), but we require `pydantic>=2` for its [Annotation Validators](https://docs.pydantic.dev/2.2/usage/validators/#annotated-validators) feature. I'd love it if the two projects could play nicely together! Currently, I'm forced to do a two-step install to get all of the `caikit` requirements, then install `vectordb` to downgrade `pydantic` which isn't ideal.

**Comment by JoanFM** [comment]
> Hi @JoanFM! Totally makes sense that `pydantic>=2` is not supported. The dependency is coming in as a transitive dep from `docarray` ([here](https://github.com/docarray/docarray/blob/main/pyproject.toml#L38)) with no upper bound, but I see it also comes in from [`jina` here](https://github.com/jina-ai/jina/blob/master/extra-requirements.txt#L55). I'm not clear how difficult it would be to fix the `jina` requirement pinning, but in `vectordb`, the fix _may_ be as simple as changing [this line](https://github.com/jina-ai/vectordb/blob/main/vectordb/utils/create_doc_type.py#L18) to `__validators__=getattr(input_doc_type, "__validators__", None)` (default to `None` if the `__validators__` attr isn't present). It's a pretty simple solution, but I haven't plumbed the depths of `vectordb`, `docarray`, or `pydantic` to understand what (if any) unintended consequences it would have.

You can try to do this change and create a PR to the repo.

As per Jina it is a little more complex

**Comment by gabe-l-hart** [comment]
Here you go! https://github.com/jina-ai/vectordb/pull/68
